# DATABASE CONFIG (AWS RDS MySQL)
spring.datasource.url=jdbc:mysql://car-rental-db.cxcaugkeofrm.us-east-2.rds.amazonaws.com:3306/car_rental?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT CONFIG
jwt.secret=myverysecuresecretkeymyverysecuresecretkey
jwt.expiration=3600000

# SERVER PORT
server.port=8080